//! The Go↔Rust interop matrix (plan step 09.4): every case runs the real `kcptun-client` and
//! `kcptun-server` binaries on loopback in all four pairings.
//!
//! ```text
//!   go → rs     Go client   ══KCP/UDP══▶  Rust server      the port's receive path
//!   rs → go     Rust client ══KCP/UDP══▶  Go server        the port's send path
//!   go → go     Go client   ══KCP/UDP══▶  Go server        control: the harness itself
//!   rs → rs     Rust client ══KCP/UDP══▶  Rust server      control: the port is self-consistent
//! ```
//!
//! **A failing control means the harness is wrong, not the port.** `go → go` runs nothing of
//! ours at all, so a red cell there is a bug in this file (or in the workload, the target server
//! or the machine); it is never a reason to change `crates/client`, `crates/server` or anything
//! below them to match. `rs → rs` failing while both crossings pass would likewise point at the
//! harness, since the crossings exercise strictly more of the port.
//!
//! # The cases
//!
//! | Group | Cases | What it covers |
//! |---|---|---|
//! | `crypt/*` | 15 | every `-crypt` method at kcptun's defaults |
//! | `pair/NN` | [`pairwise_cases`] | all 2-way combinations of compression, smux version, FEC, QPP, mode, `-conn` and MTU |
//! | `production` | 1 | the fixed profile from the plan (`-mode normal -crypt xor -mtu 1390 …`) |
//!
//! The pairwise group is generated by [`matrix::pairwise_indices`](crate::matrix::pairwise_indices)
//! over [`DIMENSIONS`], so it is deterministic: the same list, in the same order, on every run and
//! on every machine. [`case_table`] prints it as the Markdown that `docs/interop-matrix.md` is
//! regenerated from.
//!
//! `-crypt` is deliberately *not* one of the pairwise dimensions: the plan gives it its own 15
//! default-configuration cases ("All 15 crypt modes run with the defaults. The other dimensions
//! are covered pairwise"), and folding 15 levels into the expansion would force at least 60 rows
//! for no extra two-way coverage.
//!
//! # The workload
//!
//! Each run drives one [`MatrixTarget`] through the tunnel, three times:
//!
//! 1. **bulk**: one stream, [`Workload::bulk_bytes`] each way, SHA-256 verified in both
//!    directions;
//! 2. **streams**: [`Workload::streams`] concurrent streams, each a
//!    [`Workload::stream_bytes`] request/echo pair, SHA-256 verified;
//! 3. **half-close**: one stream whose answer is produced only *after* the application's
//!    `shutdown(SHUT_WR)`, so every response byte crosses a half-closed stream.
//!
//! (1) and (2) read their whole answer *before* half-closing, so they never depend on half-close
//! semantics; (3) depends on nothing else. Both processes' logs are then scanned for the
//! [`ERROR_MARKERS`] denylist: the substrings neither implementation prints in a healthy run,
//! rather than against an allowlist of known-good lines.
//!
//! # The expected Go behaviours
//!
//! Exactly one thing is allowed to differ, and only in workload (3), and only with a **Go
//! client**. Both halves of it reproduce in the `go -> go` control, which runs no Rust at all.
//!
//! * **V11**: Go's smux discards received-but-unread data when the peer's FIN completes a
//!   half-close (`tryHalfCloseCleanup` -> `streamClosed` -> `recycleTokens`), so a Go client cuts
//!   the answer at whatever was still unread in smux's buffer when the FIN landed, usually, but
//!   not always, a frame boundary. Measured here on the real binaries: 57344 of 65536 bytes
//!   (`go -> rs`) and 49152 of 65536 (`go -> go`).
//! * **V04**, with `-QPP` on top, Go's `QPPPort` implements no `CloseWrite`, so kcptun's `Pipe`
//!   falls back to a full `Close` (`std/copy.go:72`) and tears the stream down the instant the
//!   application half-closes; nothing of the answer survives.
//!
//! [`Expectation`] encodes both. Whatever does arrive must still be a correct *prefix* of the
//! expected stream, and the `pipe:` line the Go peer logs about its own torn-down stream is
//! allowed (and recorded as a note). A **Rust client is held to a complete response against
//! either server**: that is what V11 and V04 bought, and the `rs -> rs` control stays strict.
//!
//! # Running it
//!
//! ```sh
//! cargo build --release -p kcptun-client -p kcptun-server
//! tools/fetch-reference.sh --skip-latest --skip-tests     # Go reference binaries
//! cargo test -p kcptun-interop-tests --test interop_matrix -- --ignored --nocapture interop_matrix_full
//! ```
//!
//! (the trailing test name matters: without it libtest also runs `interop_matrix_smoke`, in
//! parallel with the full matrix, and the two runs would measure each other)
//!
//! `KCPTUN_INTEROP_MATRIX_FILTER=pair/07` runs one case (substring match on the case id), and
//! `KCPTUN_INTEROP_MATRIX_OUT=docs/interop-matrix.md` writes the report instead of only printing
//! it. Every process is a `Proc` and dies with its [`Tunnel`], on the panic and timeout paths too.

use std::fmt;
use std::io;
use std::net::SocketAddr;
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{Duration, Instant};

use kcptun_testkit::servers::{PrngStream, write_prng_stream};
use sha2::{Digest, Sha256};
use tokio::io::{AsyncReadExt, AsyncWriteExt};

use crate::bins::Impl;
use crate::e2e::{
    Acceptor, LocalStream, StartError, Tunnel, bind_tcp, hash_exact, panic_lines, serve,
};
use crate::matrix::{Case, Side, pairwise_indices};

/// Read size of the copies in this module.
const BUF_SIZE: usize = 64 * 1024;

// ---------------------------------------------------------------------------------------
// Keys
// ---------------------------------------------------------------------------------------

/// The `-key` every non-QPP case uses.
pub const DEFAULT_KEY: &str = "kcptun-rust interop matrix";

/// Length of [`qpp_key`], as the plan's QPP dimension specifies.
///
/// Go's `ValidateQPPParams` warns (in red) when the key is shorter than
/// `qpp.QPPMinimumSeedLength(8)`, which is 211 bytes: the byte length of `log2(256!)`. 300 bytes
/// clears it, so a QPP case starts with no warnings on either implementation and the log scan can
/// stay strict.
// Go: kcptun@v0.0.0-20260208051026-39935d5307f0 std/qpp.go:ValidateQPPParams
pub const QPP_KEY_LEN: usize = 300;

/// The `-key` every `-QPP` case uses: [`QPP_KEY_LEN`] printable ASCII bytes, fixed and
/// reproducible (no randomness anywhere in the matrix).
pub fn qpp_key() -> String {
    // '!'..'~' is 94 characters; repeating the span keeps the key printable on a command line.
    (0..QPP_KEY_LEN)
        .map(|i| (b'!' + (i % 94) as u8) as char)
        .collect()
}

// ---------------------------------------------------------------------------------------
// Pairings
// ---------------------------------------------------------------------------------------

/// Which implementation runs each end of the tunnel.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Pairing {
    /// The implementation that runs `kcptun-client`.
    pub client: Impl,
    /// The implementation that runs `kcptun-server`.
    pub server: Impl,
}

impl Pairing {
    /// `go->rs`, `rs->go`, `go->go` or `rs->rs`.
    pub fn label(self) -> String {
        format!("{}->{}", self.client.tag(), self.server.tag())
    }

    /// True for `go->go` and `rs->rs`: both ends are the same implementation, so a failure
    /// indicts the harness rather than the port (see the [module docs](self)).
    pub fn is_control(self) -> bool {
        self.client == self.server
    }
}

impl fmt::Display for Pairing {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.label())
    }
}

/// The four pairings every case runs, crossings first so a real interop failure is reported
/// before a control that the same bug would also take down.
pub const PAIRINGS: [Pairing; 4] = [
    Pairing {
        client: Impl::Go,
        server: Impl::Rust,
    },
    Pairing {
        client: Impl::Rust,
        server: Impl::Go,
    },
    Pairing {
        client: Impl::Go,
        server: Impl::Go,
    },
    Pairing {
        client: Impl::Rust,
        server: Impl::Rust,
    },
];

// ---------------------------------------------------------------------------------------
// Cases
// ---------------------------------------------------------------------------------------

/// Which part of the matrix a case belongs to.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Group {
    /// One case per `-crypt` method, everything else at kcptun's defaults.
    Crypt,
    /// The pairwise expansion of [`DIMENSIONS`].
    Pairwise,
    /// The plan's fixed production profile.
    Production,
}

impl Group {
    /// `crypt`, `pairwise` or `production`.
    pub fn name(self) -> &'static str {
        match self {
            Group::Crypt => "crypt",
            Group::Pairwise => "pairwise",
            Group::Production => "production",
        }
    }
}

impl fmt::Display for Group {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

/// One matrix case: the two command lines (they differ for the FEC-mismatch case) and the key.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InteropCase {
    /// Stable identifier, e.g. `crypt/salsa20`, `pair/07`, `production`.
    pub id: String,
    /// Which part of the matrix this case belongs to.
    pub group: Group,
    /// `dimension=value` list for the pairwise group, or a short description otherwise.
    pub summary: String,
    /// The client's configuration.
    pub client: Case,
    /// The server's configuration.
    pub server: Case,
    /// The `-key` both sides are given.
    pub key: String,
}

impl InteropCase {
    /// True when `-QPP` is on (both sides always agree about that).
    pub fn qpp(&self) -> bool {
        self.client.qpp
    }

    /// The exact configuration, as several lines: what a failing case prints so it can be
    /// reproduced by hand.
    pub fn describe(&self) -> String {
        format!(
            "case {id} (group {group})\n  {summary}\n  key: {key} ({keylen} bytes)\n  \
             client: {client}\n  server: {server}\n  client flags: {cargs}\n  server flags: {sargs}",
            id = self.id,
            group = self.group,
            summary = self.summary,
            key = if self.key.len() > 40 {
                format!("{}…", &self.key[..40])
            } else {
                self.key.clone()
            },
            keylen = self.key.len(),
            client = self.client.label(),
            server = self.server.label(),
            cargs = self.client.args(Side::Client).join(" "),
            sargs = self.server.args(Side::Server).join(" "),
        )
    }
}

/// A client/server configuration pair under construction; what a [`Level`] mutates.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Pair {
    /// The client's configuration.
    pub client: Case,
    /// The server's configuration.
    pub server: Case,
    /// The `-key` both sides are given.
    pub key: String,
}

impl Pair {
    /// kcptun's defaults on both sides with [`DEFAULT_KEY`].
    pub fn defaults() -> Self {
        Pair {
            client: Case::new(),
            server: Case::new(),
            key: DEFAULT_KEY.to_string(),
        }
    }

    /// Applies `f` to both sides.
    fn both(&mut self, f: impl Fn(&mut Case)) {
        f(&mut self.client);
        f(&mut self.server);
    }
}

/// One value of one pairwise [`Dimension`].
#[derive(Clone, Copy)]
pub struct Level {
    /// Short name used in [`InteropCase::summary`] and in the generated Markdown.
    pub name: &'static str,
    /// How this value changes the pair.
    pub apply: fn(&mut Pair),
}

impl fmt::Debug for Level {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name)
    }
}

/// One dimension of the pairwise part of the matrix.
#[derive(Clone, Copy, Debug)]
pub struct Dimension {
    /// Short name used in [`InteropCase::summary`] and in the generated Markdown.
    pub name: &'static str,
    /// The values it takes.
    pub levels: &'static [Level],
}

/// The pairwise dimensions, exactly the plan's table minus `crypt` (see the [module docs](self)).
///
/// The order is fixed because the case list must be: the generator is deterministic given these
/// level counts, so reordering the table would renumber `pair/NN`.
pub static DIMENSIONS: &[Dimension] = &[
    Dimension {
        name: "comp",
        levels: &[
            Level {
                name: "snappy",
                apply: |p: &mut Pair| p.both(|c| c.nocomp = false),
            },
            Level {
                name: "nocomp",
                apply: |p: &mut Pair| p.both(|c| c.nocomp = true),
            },
        ],
    },
    Dimension {
        name: "smuxver",
        levels: &[
            Level {
                name: "1",
                apply: |p: &mut Pair| p.both(|c| c.smuxver = 1),
            },
            Level {
                name: "2",
                apply: |p: &mut Pair| p.both(|c| c.smuxver = 2),
            },
        ],
    },
    Dimension {
        name: "fec",
        levels: &[
            Level {
                name: "10/3",
                apply: |p: &mut Pair| p.both(|c| (c.ds, c.ps) = (10, 3)),
            },
            Level {
                name: "off",
                apply: |p: &mut Pair| p.both(|c| (c.ds, c.ps) = (0, 0)),
            },
            Level {
                name: "3/2",
                apply: |p: &mut Pair| p.both(|c| (c.ds, c.ps) = (3, 2)),
            },
            // The plan's FEC mismatch: kcp-go's decoder autotunes to whatever the peer sends, so
            // a client on 10/3 and a server on 5/2 must still interoperate.
            Level {
                name: "10/3-vs-5/2",
                apply: |p: &mut Pair| {
                    (p.client.ds, p.client.ps) = (10, 3);
                    (p.server.ds, p.server.ps) = (5, 2);
                },
            },
        ],
    },
    Dimension {
        name: "qpp",
        levels: &[
            Level {
                name: "off",
                apply: |p: &mut Pair| p.both(|c| c.qpp = false),
            },
            // 61 is kcptun's default pad count; 7 is `qpp.QPPMinimumPads(8)`, the smallest value
            // that draws no warning. Both need a key of at least 211 bytes.
            Level {
                name: "on/61",
                apply: |p: &mut Pair| {
                    p.both(|c| {
                        c.qpp = true;
                        c.extra.extend(["-QPPCount".to_string(), "61".to_string()]);
                    });
                    p.key = qpp_key();
                },
            },
            Level {
                name: "on/7",
                apply: |p: &mut Pair| {
                    p.both(|c| {
                        c.qpp = true;
                        c.extra.extend(["-QPPCount".to_string(), "7".to_string()]);
                    });
                    p.key = qpp_key();
                },
            },
        ],
    },
    Dimension {
        name: "mode",
        levels: &[
            Level {
                name: "fast",
                apply: |p: &mut Pair| p.both(|c| c.mode = "fast".into()),
            },
            Level {
                name: "fast3",
                apply: |p: &mut Pair| p.both(|c| c.mode = "fast3".into()),
            },
            Level {
                name: "normal",
                apply: |p: &mut Pair| p.both(|c| c.mode = "normal".into()),
            },
            // `manual` is the one mode kcptun's ApplyMode() leaves alone, so the four knobs come
            // from the flags themselves.
            // Go: kcptun@v0.0.0-20260208051026-39935d5307f0 std/config.go:BaseConfig.ApplyMode
            Level {
                name: "manual 1 10 2 1",
                apply: |p: &mut Pair| {
                    p.both(|c| {
                        c.mode = "manual".into();
                        c.extra.extend(
                            [
                                "-nodelay",
                                "1",
                                "-interval",
                                "10",
                                "-resend",
                                "2",
                                "-nc",
                                "1",
                            ]
                            .map(String::from),
                        );
                    });
                },
            },
        ],
    },
    Dimension {
        name: "conn",
        levels: &[
            Level {
                name: "1",
                apply: |p: &mut Pair| p.client.conn = 1,
            },
            Level {
                name: "4",
                apply: |p: &mut Pair| p.client.conn = 4,
            },
        ],
    },
    Dimension {
        name: "mtu",
        levels: &[
            Level {
                name: "1350",
                apply: |p: &mut Pair| p.both(|c| c.mtu = 1350),
            },
            Level {
                name: "1400",
                apply: |p: &mut Pair| p.both(|c| c.mtu = 1400),
            },
        ],
    },
];

/// Every `-crypt` method kcptun accepts, in the order its `--crypt` help text lists them.
///
/// The same 15 names as [`kcp::CRYPT_MODES`](crate::kcp::CRYPT_MODES), which the raw-KCP interop
/// suite uses in its own order; `every_crypt_mode_gets_a_default_case` pins the two lists equal as
/// sets, so a method can never be covered in one suite and forgotten in the other.
// Go: kcptun@v0.0.0-20260208051026-39935d5307f0 client/main.go, server/main.go: cli flag `crypt`
pub const CRYPT_MODES: [&str; 15] = [
    "aes",
    "aes-128",
    "aes-192",
    "aes-128-gcm",
    "salsa20",
    "blowfish",
    "twofish",
    "cast5",
    "3des",
    "tea",
    "xtea",
    "xor",
    "sm4",
    "none",
    "null",
];

/// One case per `-crypt` method, everything else at kcptun's defaults.
pub fn crypt_cases() -> Vec<InteropCase> {
    CRYPT_MODES
        .iter()
        .map(|&crypt| InteropCase {
            id: format!("crypt/{crypt}"),
            group: Group::Crypt,
            summary: format!("crypt={crypt}, everything else default"),
            client: Case::new().crypt(crypt),
            server: Case::new().crypt(crypt),
            key: DEFAULT_KEY.to_string(),
        })
        .collect()
}

/// The pairwise expansion of [`DIMENSIONS`]: every pair of values of any two dimensions appears
/// in at least one case. Deterministic: the same list in the same order on every run.
pub fn pairwise_cases() -> Vec<InteropCase> {
    let levels: Vec<usize> = DIMENSIONS.iter().map(|d| d.levels.len()).collect();
    pairwise_indices(&levels)
        .into_iter()
        .enumerate()
        .map(|(n, row)| {
            let mut pair = Pair::defaults();
            let mut parts: Vec<String> = Vec::with_capacity(DIMENSIONS.len());
            for (dim, &i) in DIMENSIONS.iter().zip(&row) {
                let level = dim.levels[i];
                (level.apply)(&mut pair);
                parts.push(format!("{}={}", dim.name, level.name));
            }
            InteropCase {
                id: format!("pair/{:02}", n + 1),
                group: Group::Pairwise,
                summary: parts.join(" "),
                client: pair.client,
                server: pair.server,
                key: pair.key,
            }
        })
        .collect()
}

/// The plan's fixed production profile.
///
/// `-mode normal --crypt xor --mtu 1390 --sndwnd 8192 --rcvwnd 8192 --smuxver 2 --smuxbuf
/// 16777216 --streambuf 16777216 --datashard 0 --parityshard 0 --nocomp --quiet`, with the client
/// on `--conn 4 --sockbuf 8388608` and the server on `--sockbuf 67108868` (the plan's value; it is
/// not a round number, and it is copied exactly).
pub fn production_case() -> InteropCase {
    let base = Case::new()
        .crypt("xor")
        .mode("normal")
        .mtu(1390)
        .smuxver(2)
        .fec(0, 0)
        .nocomp(true)
        .extra_args([
            "-sndwnd",
            "8192",
            "-rcvwnd",
            "8192",
            "-smuxbuf",
            "16777216",
            "-streambuf",
            "16777216",
            "-quiet",
        ]);
    InteropCase {
        id: "production".to_string(),
        group: Group::Production,
        summary: "the plan's fixed production profile".to_string(),
        client: base.clone().conn(4).extra_args(["-sockbuf", "8388608"]),
        server: base.extra_args(["-sockbuf", "67108868"]),
        key: DEFAULT_KEY.to_string(),
    }
}

/// Every case of the matrix: [`crypt_cases`], then [`pairwise_cases`], then [`production_case`].
pub fn all_cases() -> Vec<InteropCase> {
    let mut v = crypt_cases();
    v.extend(pairwise_cases());
    v.push(production_case());
    v
}

/// The cases whose id contains `filter` (the whole list when it is empty).
pub fn select(cases: Vec<InteropCase>, filter: &str) -> Vec<InteropCase> {
    if filter.is_empty() {
        return cases;
    }
    cases
        .into_iter()
        .filter(|c| c.id.contains(filter))
        .collect()
}

// ---------------------------------------------------------------------------------------
// Expectations
// ---------------------------------------------------------------------------------------

/// What the half-close workload may produce for one (case, pairing).
///
/// Only a **Go client** can truncate, and it can do so for two independent reasons; both are
/// correct Go behaviour, and both are recorded in `docs/DECISIONS.md`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Expectation {
    /// The whole response must arrive, in order, hash-verified. This is what a **Rust** client
    /// owes against either server, with or without `-QPP`.
    Complete,
    /// **V11**, a Go client without `-QPP`: once the application half-closes and the peer's FIN
    /// arrives, Go's smux runs `tryHalfCloseCleanup` → `streamClosed` → `recycleTokens`, which
    /// discards everything received but not yet read. The reader then sees EOF early, so the
    /// answer is cut at whatever was still buffered, usually, but not always, a frame boundary.
    ///
    /// Any length is accepted, including `0`, which makes such a row no stronger a statement than
    /// "what arrived was a correct prefix". In practice V11 cuts only what smux still holds when
    /// the FIN lands, so a real row is far from zero (the lowest seen in 256 committed runs is
    /// 8192); a `0` is therefore noted in the report as worth a look rather than passed silently.
    // Go: smux@v1.5.55 stream.go:tryHalfCloseCleanup, session.go:streamClosed
    GoSmuxTruncation,
    /// **V04 on top of V11**, a Go client with `-QPP`: `std.QPPPort` implements no `CloseWrite`,
    /// so kcptun's `Pipe` falls back to `Close()` and tears the whole stream down the moment the
    /// application half-closes. Nothing of an answer that starts afterwards survives.
    // Go: kcptun@v0.0.0-20260208051026-39935d5307f0 std/qpp.go:QPPPort, std/copy.go:Pipe
    GoQppTruncation,
}

impl Expectation {
    /// The expectation for `case` under `pairing`.
    pub fn of(case: &InteropCase, pairing: Pairing) -> Self {
        match (pairing.client, case.qpp()) {
            (Impl::Go, true) => Expectation::GoQppTruncation,
            (Impl::Go, false) => Expectation::GoSmuxTruncation,
            (Impl::Rust, _) => Expectation::Complete,
        }
    }

    /// True when a short response is not a failure.
    pub fn allows_truncation(self) -> bool {
        self != Expectation::Complete
    }

    /// Short tag for the report.
    pub fn tag(self) -> &'static str {
        match self {
            Expectation::Complete => "complete",
            Expectation::GoSmuxTruncation => "V11",
            Expectation::GoQppTruncation => "V04+V11",
        }
    }
}

// ---------------------------------------------------------------------------------------
// The target server
// ---------------------------------------------------------------------------------------

/// Size of a [`MatrixTarget`] request header.
const HEADER_LEN: usize = 24;
/// Magic at the front of a [`MatrixTarget`] request header.
const MAGIC: [u8; 4] = *b"KMX1";
/// Header mode: echo everything that follows.
const MODE_ECHO: u8 = 1;
/// Header mode: read to EOF, then answer.
const MODE_RESPOND: u8 = 2;

/// What the application asks a [`MatrixTarget`] connection to do.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum TargetMode {
    /// Echo every byte after the header back.
    Echo,
    /// Read the rest of the request to EOF, then send `len` bytes of `PrngStream(seed)`.
    Respond { seed: u64, len: u64 },
}

impl TargetMode {
    /// The 24-byte header that selects this mode.
    fn header(self) -> [u8; HEADER_LEN] {
        let mut h = [0u8; HEADER_LEN];
        h[..4].copy_from_slice(&MAGIC);
        match self {
            TargetMode::Echo => h[4] = MODE_ECHO,
            TargetMode::Respond { seed, len } => {
                h[4] = MODE_RESPOND;
                h[8..16].copy_from_slice(&seed.to_le_bytes());
                h[16..24].copy_from_slice(&len.to_le_bytes());
            }
        }
        h
    }

    /// Parses a header, or `None` if it is not one of ours.
    fn parse(h: &[u8; HEADER_LEN]) -> Option<Self> {
        if h[..4] != MAGIC {
            return None;
        }
        let seed = u64::from_le_bytes(h[8..16].try_into().ok()?);
        let len = u64::from_le_bytes(h[16..24].try_into().ok()?);
        match h[4] {
            MODE_ECHO => Some(TargetMode::Echo),
            MODE_RESPOND => Some(TargetMode::Respond { seed, len }),
            _ => None,
        }
    }
}

/// The matrix's one target server: it serves all three workloads, so a case needs a single `-t`.
///
/// Every connection starts with a [`HEADER_LEN`]-byte header naming the mode. `Echo` is the
/// ordinary echo target the bulk and concurrent-stream workloads use; `Respond` reads the request
/// to EOF and only *then* answers, which is what puts every response byte on a half-closed
/// stream.
#[derive(Debug)]
pub struct MatrixTarget {
    addr: SocketAddr,
    connections: Arc<AtomicU64>,
    bad_headers: Arc<AtomicU64>,
    acceptor: Acceptor,
}

impl MatrixTarget {
    /// Starts the target on `127.0.0.1` with an ephemeral port.
    pub async fn start() -> io::Result<Self> {
        let (listener, addr) = bind_tcp().await?;
        let connections = Arc::new(AtomicU64::new(0));
        let bad_headers = Arc::new(AtomicU64::new(0));
        let conns = Arc::clone(&connections);
        let bad = Arc::clone(&bad_headers);
        let acceptor = serve(listener, move |mut conn| {
            conns.fetch_add(1, Ordering::SeqCst);
            let bad = Arc::clone(&bad);
            async move {
                let mut header = [0u8; HEADER_LEN];
                if conn.read_exact(&mut header).await.is_err() {
                    bad.fetch_add(1, Ordering::SeqCst);
                    return;
                }
                let Some(mode) = TargetMode::parse(&header) else {
                    bad.fetch_add(1, Ordering::SeqCst);
                    return;
                };
                match mode {
                    TargetMode::Echo => {
                        let mut buf = vec![0u8; BUF_SIZE];
                        loop {
                            match conn.read(&mut buf).await {
                                Ok(0) => break,
                                Ok(n) => {
                                    if conn.write_all(&buf[..n]).await.is_err() {
                                        return;
                                    }
                                }
                                Err(_) => return,
                            }
                        }
                        let _ = conn.shutdown().await;
                    }
                    TargetMode::Respond { seed, len } => {
                        let mut sink = vec![0u8; BUF_SIZE];
                        loop {
                            match conn.read(&mut sink).await {
                                Ok(0) => break,
                                Ok(_) => {}
                                Err(_) => return,
                            }
                        }
                        if write_prng_stream(&mut conn, seed, len).await.is_ok() {
                            let _ = conn.shutdown().await;
                        }
                    }
                }
                // Drain until the peer closes, so a complete answer is never turned into a reset.
                let mut sink = [0u8; 1024];
                while matches!(conn.read(&mut sink).await, Ok(n) if n > 0) {}
            }
        });
        Ok(MatrixTarget {
            addr,
            connections,
            bad_headers,
            acceptor,
        })
    }

    /// The `-t` value for this target.
    pub fn target(&self) -> String {
        self.addr.to_string()
    }

    /// Connections accepted so far.
    pub fn connections(&self) -> u64 {
        self.connections.load(Ordering::SeqCst)
    }

    /// Connections that did not start with a readable header: a tunnel that corrupts or
    /// reorders the first bytes shows up here rather than as a silent hang.
    pub fn bad_headers(&self) -> u64 {
        self.bad_headers.load(Ordering::SeqCst)
    }

    /// Stops accepting and shuts every open connection down.
    pub async fn shutdown(mut self) {
        self.acceptor.shutdown().await;
    }
}

// ---------------------------------------------------------------------------------------
// The workload
// ---------------------------------------------------------------------------------------

/// How much traffic one run pushes through the tunnel.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Workload {
    /// Bytes sent **and** echoed back on the single bulk stream.
    pub bulk_bytes: u64,
    /// How many concurrent short streams to open.
    pub streams: usize,
    /// Bytes sent and echoed back on each of those streams.
    pub stream_bytes: u64,
    /// Bytes the half-close probe asks for after it has shut its write side.
    pub response_bytes: u64,
    /// Bytes the half-close probe sends before shutting its write side.
    pub request_bytes: u64,
    /// How long the half-close probe waits after `shutdown(SHUT_WR)` before it starts reading.
    ///
    /// The delay is what makes the probe *decisive* rather than a race: while it runs, the whole
    /// answer and the peer's FIN pile up in the stream's receive buffer, which is exactly the
    /// state in which Go's `recycleTokens` throws them away (V11). A Rust client must still hand
    /// over every byte, so the strict side of the matrix gets harder, not easier, and a Go
    /// client's truncation stops depending on how fast the machine happens to be.
    pub half_close_read_delay: Duration,
}

/// The plan's workload: 20 MB bulk each way plus 100 concurrent small streams, and the
/// half-close probe on top.
pub const FULL: Workload = Workload {
    bulk_bytes: 20 * 1000 * 1000,
    streams: 100,
    stream_bytes: 16 * 1024,
    response_bytes: 256 * 1024,
    request_bytes: 4 * 1024,
    half_close_read_delay: Duration::from_millis(250),
};

/// A smaller workload for a quick check of the harness itself.
pub const SMOKE: Workload = Workload {
    bulk_bytes: 1 << 20,
    streams: 8,
    stream_bytes: 4 * 1024,
    response_bytes: 64 * 1024,
    request_bytes: 1024,
    half_close_read_delay: Duration::from_millis(250),
};

/// Writes a [`MatrixTarget`] header.
async fn send_header<W: tokio::io::AsyncWrite + Unpin>(
    w: &mut W,
    mode: TargetMode,
) -> io::Result<()> {
    w.write_all(&mode.header()).await
}

/// One echo exchange: header, `len` bytes out and `len` bytes back, SHA-256 verified, then a
/// half-close and the end of the stream.
///
/// The answer is read in full *before* the half-close, so this workload does not depend on
/// half-close semantics at all: that is what the third workload is for.
async fn echo_exchange(stream: &mut LocalStream, seed: u64, len: u64) -> Result<(), String> {
    let (send, sha) = {
        let (mut r, mut w) = tokio::io::split(&mut *stream);
        let send = async {
            send_header(&mut w, TargetMode::Echo).await?;
            write_prng_stream(&mut w, seed, len).await
        };
        // Both halves run in this task; `tokio::spawn` would need a `'static` stream.
        tokio::join!(send, hash_exact(&mut r, len))
    };
    match (sha, send) {
        (Ok(sha), Ok(())) => {
            if sha != PrngStream::sha256_hex(seed, len) {
                return Err(format!(
                    "echo of {len} bytes (seed {seed}) came back with SHA-256 {sha}, expected {}",
                    PrngStream::sha256_hex(seed, len)
                ));
            }
        }
        (Ok(_), Err(e)) => return Err(format!("sending {len} bytes: {e}")),
        (Err(e), Ok(())) => return Err(format!("reading the echo of {len} bytes: {e}")),
        (Err(e), Err(w)) => {
            return Err(format!(
                "reading the echo of {len} bytes: {e} (request: {w})"
            ));
        }
    }
    stream
        .shutdown()
        .await
        .map_err(|e| format!("half-closing after the echo: {e}"))?;
    end_of_stream(stream).await
}

/// Fails unless the stream ends now.
///
/// A reset counts: the application has already read every byte it asked for, both kcptun peers
/// are tearing the stream down, and whether the last `close(2)` lands as a FIN or an RST on
/// loopback is a race with no bearing on data integrity. Anything else (a stray byte) is a
/// failure.
async fn end_of_stream(stream: &mut LocalStream) -> Result<(), String> {
    let mut buf = [0u8; 64];
    match stream.read(&mut buf).await {
        Ok(0) => Ok(()),
        Ok(n) => Err(format!(
            "{n} unexpected bytes after the end of the stream: {:?}",
            &buf[..n.min(16)]
        )),
        Err(e) if e.kind() == io::ErrorKind::ConnectionReset => Ok(()),
        Err(e) => Err(format!("waiting for the end of the stream: {e}")),
    }
}

/// The half-close probe: send a request, `shutdown(SHUT_WR)`, then read the answer the target
/// only starts producing once it has seen that EOF.
///
/// Returns how many response bytes arrived. Every byte that arrives is checked against the
/// expected stream as it arrives, so a truncation allowed by [`Expectation`] still cannot hide
/// corruption: a wrong byte fails the run whatever the expectation says.
async fn half_close_probe(
    stream: &mut LocalStream,
    seed: u64,
    len: u64,
    request_bytes: u64,
    read_delay: Duration,
    expected: &[u8],
) -> Result<u64, String> {
    send_header(stream, TargetMode::Respond { seed, len })
        .await
        .map_err(|e| format!("half-close probe: sending the header: {e}"))?;
    write_prng_stream(stream, seed ^ 0x5a5a, request_bytes)
        .await
        .map_err(|e| format!("half-close probe: sending the request: {e}"))?;
    stream
        .shutdown()
        .await
        .map_err(|e| format!("half-close probe: shutdown(SHUT_WR): {e}"))?;
    // Let the answer and the peer's FIN arrive before reading a byte of either; see
    // `Workload::half_close_read_delay`.
    tokio::time::sleep(read_delay).await;

    let mut got: Vec<u8> = Vec::with_capacity(expected.len());
    let mut buf = vec![0u8; BUF_SIZE];
    loop {
        let n = match stream.read(&mut buf).await {
            Ok(0) => break,
            Ok(n) => n,
            // The peer resetting after a V04 teardown is the truncation itself, not a new fault;
            // the caller decides whether the resulting length is acceptable.
            Err(e) if e.kind() == io::ErrorKind::ConnectionReset => break,
            Err(e) => return Err(format!("half-close probe: reading the response: {e}")),
        };
        if got.len() + n > expected.len() {
            return Err(format!(
                "half-close probe: the response is longer than the {} bytes asked for",
                expected.len()
            ));
        }
        if buf[..n] != expected[got.len()..got.len() + n] {
            let at = got.len()
                + buf[..n]
                    .iter()
                    .zip(&expected[got.len()..])
                    .position(|(a, b)| a != b)
                    .unwrap_or(0);
            return Err(format!(
                "half-close probe: the response differs from the expected stream at byte {at}"
            ));
        }
        got.extend_from_slice(&buf[..n]);
    }
    Ok(got.len() as u64)
}

// ---------------------------------------------------------------------------------------
// Running a case
// ---------------------------------------------------------------------------------------

/// How long one case may take before it is called a failure.
pub const CASE_TIMEOUT: Duration = Duration::from_secs(240);

/// Log substrings that mean something went wrong. None of them occurs in a healthy run of either
/// implementation, whose output is startup lines plus `stream opened` / `stream closed`.
// Go: kcptun@v0.0.0-20260208051026-39935d5307f0 client/main.go, server/main.go (log sites)
const ERROR_MARKERS: &[&str] = &[
    "panicked at",
    "fatal runtime error",
    "pipe:",
    "re-connecting:",
    "SetDSCP:",
    "SetReadBuffer:",
    "SetWriteBuffer:",
    "Warning",
    "WARNING",
    "scavenger:",
];

/// The lines of `log` that match [`ERROR_MARKERS`].
pub fn error_lines(log: &str) -> Vec<&str> {
    log.lines()
        .filter(|l| ERROR_MARKERS.iter().any(|m| l.contains(m)))
        .collect()
}

/// The result of one (case, pairing) run.
#[derive(Clone, Debug)]
pub struct RunReport {
    /// [`InteropCase::id`].
    pub case_id: String,
    /// Which pairing ran.
    pub pairing: Pairing,
    /// What the half-close workload was allowed to do.
    pub expectation: Expectation,
    /// How many response bytes the half-close probe received.
    pub half_close_bytes: u64,
    /// How many it asked for ([`Workload::response_bytes`]).
    pub response_bytes: u64,
    /// How long the whole run took.
    pub elapsed: Duration,
    /// Anything worth recording that is not a failure (e.g. an observed V04 truncation).
    pub notes: Vec<String>,
}

impl RunReport {
    /// The table cell: `ok` for a strict run, or `ok (V11 253952/262144)` for one where a Go
    /// client was allowed to truncate: the numbers say how much of the half-close answer
    /// survived, so `262144/262144` means the expected truncation did not happen on this run.
    pub fn status(&self) -> String {
        match self.expectation {
            Expectation::Complete => "ok".to_string(),
            e => format!(
                "ok ({} {}/{})",
                e.tag(),
                self.half_close_bytes,
                self.response_bytes
            ),
        }
    }

    /// [`status`](Self::status) plus anything else worth seeing on the console.
    pub fn detail(&self) -> String {
        if self.notes.is_empty() {
            self.status()
        } else {
            format!("{} [{}]", self.status(), self.notes.join("; "))
        }
    }
}

/// Runs one (case, pairing): brings the tunnel up, drives all three workloads, checks both logs
/// and tears everything down.
///
/// The error string always starts with [`InteropCase::describe`], so a failing case in a
/// 100-plus-run matrix can be reproduced from the test output alone.
pub async fn run_case(
    case: &InteropCase,
    pairing: Pairing,
    workload: &Workload,
) -> Result<RunReport, String> {
    let started = Instant::now();
    match tokio::time::timeout(CASE_TIMEOUT, run_case_inner(case, pairing, workload)).await {
        Ok(Ok(mut report)) => {
            report.elapsed = started.elapsed();
            Ok(report)
        }
        Ok(Err(e)) => Err(format!(
            "{}\n  pairing: {pairing}\n  FAILED after {:?}: {e}",
            case.describe(),
            started.elapsed()
        )),
        Err(_) => Err(format!(
            "{}\n  pairing: {pairing}\n  TIMED OUT after {CASE_TIMEOUT:?}",
            case.describe()
        )),
    }
}

/// [`run_case`] without the timeout and the configuration dump.
async fn run_case_inner(
    case: &InteropCase,
    pairing: Pairing,
    workload: &Workload,
) -> Result<RunReport, String> {
    let expectation = Expectation::of(case, pairing);
    let target = MatrixTarget::start()
        .await
        .map_err(|e| format!("starting the target server: {e}"))?;

    let mut tunnel = Tunnel::builder(target.target())
        .client_case(case.client.clone())
        .server_case(case.server.clone())
        .client_impl(pairing.client)
        .server_impl(pairing.server)
        .key(case.key.clone())
        // Every stream of this matrix is torn down by the application, and `-closewait` delays
        // exactly that teardown by its full number of seconds per direction. The default of 30 s
        // would add minutes per case and pins nothing this matrix is about: 09.3's
        // `e2e_closewait_delays_the_half_close_of_the_target` owns that behaviour.
        .server_args(["-closewait", "0"])
        .start()
        .await
        .map_err(|e: StartError| format!("starting the tunnel: {e}"))?;

    let result = drive(&mut tunnel, workload, expectation).await;
    let (half_close_bytes, mut notes) = match result {
        Ok(v) => v,
        Err(e) => {
            // The logs say far more than the I/O error on its own does.
            return Err(format!("{e}\n{}", logs_of(&tunnel)));
        }
    };

    if expectation == Expectation::GoSmuxTruncation && half_close_bytes == 0 {
        // V11 cuts what is still unread in smux's buffer, so it does not normally take the whole
        // answer: a zero here looks like V04's total loss without `-QPP` to explain it. It is
        // still a correct (empty) prefix, so it is not a failure, but it is worth a look.
        notes.push(
            "the half-close probe returned 0 bytes on a V11 row; V11 normally cuts only part of \
             the answer, so compare this crossing with its go->go control"
                .to_string(),
        );
    }

    tunnel.check_alive()?;
    if target.bad_headers() != 0 {
        return Err(format!(
            "{} target connections did not start with a readable header",
            target.bad_headers()
        ));
    }
    check_target_connections(&target, workload, half_close_bytes, expectation).await?;
    check_logs(&tunnel, expectation, &mut notes)?;
    target.shutdown().await;

    Ok(RunReport {
        case_id: case.id.clone(),
        pairing,
        expectation,
        half_close_bytes,
        response_bytes: workload.response_bytes,
        elapsed: Duration::ZERO,
        notes,
    })
}

/// Runs the three workloads over an already-started tunnel. Returns the half-close response
/// length and any notes.
async fn drive(
    tunnel: &mut Tunnel,
    workload: &Workload,
    expectation: Expectation,
) -> Result<(u64, Vec<String>), String> {
    // 1. Bulk, one stream, `bulk_bytes` each way.
    let mut app = tunnel
        .connect()
        .await
        .map_err(|e| format!("bulk: connecting to the client: {e}"))?;
    echo_exchange(&mut app, 0xB0_1C, workload.bulk_bytes)
        .await
        .map_err(|e| format!("bulk: {e}"))?;
    drop(app);

    // 2. `streams` concurrent short streams.
    let mut tasks = Vec::with_capacity(workload.streams);
    for i in 0..workload.streams {
        let endpoint = tunnel.local().clone();
        let len = workload.stream_bytes;
        let seed = 0x51EA_u64.wrapping_add(i as u64);
        tasks.push(tokio::spawn(async move {
            let mut app = crate::e2e::connect_local(&endpoint)
                .await
                .map_err(|e| format!("stream {i}: connecting to the client: {e}"))?;
            echo_exchange(&mut app, seed, len)
                .await
                .map_err(|e| format!("stream {i}: {e}"))
        }));
    }
    let mut first_error: Option<String> = None;
    for task in tasks {
        let failure = match task.await {
            Ok(Ok(())) => continue,
            Ok(Err(e)) => e,
            Err(e) => format!("stream task: {e}"),
        };
        // Every task is awaited even after the first failure, so no stream is left running.
        first_error.get_or_insert(failure);
    }
    if let Some(e) = first_error {
        return Err(e);
    }

    // 3. The half-close probe.
    let seed = 0xA1F0_u64;
    let expected = PrngStream::to_vec(seed, workload.response_bytes as usize);
    let mut app = tunnel
        .connect()
        .await
        .map_err(|e| format!("half-close: connecting to the client: {e}"))?;
    let got = half_close_probe(
        &mut app,
        seed,
        workload.response_bytes,
        workload.request_bytes,
        workload.half_close_read_delay,
        &expected,
    )
    .await?;
    drop(app);

    // A short answer is a failure unless the expectation names the Go behaviour that shortens
    // it; when it does, the report's byte count says how much survived.
    if got != workload.response_bytes && !expectation.allows_truncation() {
        return Err(format!(
            "half-close probe: {got} of {} response bytes arrived; a complete response is \
             required here",
            workload.response_bytes
        ));
    }
    Ok((got, Vec::new()))
}

/// The workload is only worth what it actually pushed through, so the target's own count has to
/// agree: one bulk stream, [`Workload::streams`] concurrent ones, and the half-close probe.
///
/// The probe's connection is the one exception. When `-QPP` makes a Go client close the stream
/// outright (V04) the application sees EOF as soon as the *client* gives up, which can be before
/// the server has finished dialling the target, and since no response byte arrives there is
/// nothing to wait for. Such a run therefore requires only that the dial has not produced a
/// *spurious* extra connection. Every other run must show all of them, after a short grace period
/// for the server's dial.
async fn check_target_connections(
    target: &MatrixTarget,
    workload: &Workload,
    half_close_bytes: u64,
    expectation: Expectation,
) -> Result<(), String> {
    let all = workload.streams as u64 + 2;
    let probe_certain = half_close_bytes > 0 || !expectation.allows_truncation();
    let required = if probe_certain { all } else { all - 1 };
    let deadline = Instant::now() + Duration::from_secs(5);
    while target.connections() < required && Instant::now() < deadline {
        tokio::time::sleep(Duration::from_millis(20)).await;
    }
    let seen = target.connections();
    if seen < required {
        return Err(format!(
            "the target saw {seen} connections, expected at least {required} (1 bulk + {} \
             concurrent + {} half-close)",
            workload.streams,
            u8::from(probe_certain)
        ));
    }
    if seen > all {
        return Err(format!(
            "the target saw {seen} connections, more than the {all} the workload opens"
        ));
    }
    Ok(())
}

/// Both processes' logs, labelled, for a failure message.
fn logs_of(tunnel: &Tunnel) -> String {
    format!(
        "--- client ({}) ---\n{}--- server ({}) ---\n{}",
        tunnel.client_impl(),
        tunnel.client_log(),
        tunnel.server_impl(),
        tunnel.server_log()
    )
}

/// Fails on any log line matching the [`ERROR_MARKERS`] denylist.
///
/// This is a denylist, not an allowlist: a line neither implementation prints in a healthy run
/// fails the case, but a log site that reports its error bare (Go's `server/main.go` does so for
/// `smux.Server`, `mux.AcceptStream` and the target dial) would pass unnoticed. Those failures
/// are caught by the workload instead, no byte of the response would arrive.
fn check_logs(
    tunnel: &Tunnel,
    expectation: Expectation,
    notes: &mut Vec<String>,
) -> Result<(), String> {
    for (what, log) in [
        ("client", tunnel.client_log()),
        ("server", tunnel.server_log()),
    ] {
        let panics = panic_lines(&log);
        if !panics.is_empty() {
            return Err(format!("{what} panicked:\n{}", panics.join("\n")));
        }
        let bad: Vec<&str> = error_lines(&log)
            .into_iter()
            // A Go client tears its own half-closed stream down (V11, and V04 as well with
            // `-QPP`), so the reverse copy of its own `Pipe` ends with an error rather than EOF
            // and kcptun logs it. That `pipe:` line *is* the expected behaviour, not a second
            // fault. Everything else still fails, on both sides.
            .filter(|l| !(expectation.allows_truncation() && l.contains("pipe:")))
            .collect();
        if !bad.is_empty() {
            return Err(format!(
                "{what} logged {} unexpected line(s):\n{}",
                bad.len(),
                bad.join("\n")
            ));
        }
        if expectation.allows_truncation() && log.lines().any(|l| l.contains("pipe:")) {
            notes.push(format!("{what} logged `pipe:` for the torn-down stream"));
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------------------
// The report
// ---------------------------------------------------------------------------------------

/// `20 MB`, `256 KiB`, `1024 B`, whichever reads best for `n`.
fn bytes_human(n: u64) -> String {
    if n >= 1_000_000 && n.is_multiple_of(1_000_000) {
        format!("{} MB", n / 1_000_000)
    } else if n >= 1024 && n.is_multiple_of(1024) {
        format!("{} KiB", n / 1024)
    } else {
        format!("{n} B")
    }
}

/// Wall time per pairing, with each one's slowest case.
///
/// The interesting column is the total: `rs->rs` against `go->go` is the cheapest honest
/// comparison this matrix offers, since both run the same cases over the same loopback.
pub fn timing_table(results: &[CaseResult]) -> String {
    let mut s = String::new();
    s.push_str("| Pairing | Runs | Total | Slowest case |\n|---|---|---|---|\n");
    for p in PAIRINGS {
        let runs: Vec<&RunReport> = results
            .iter()
            .filter(|r| r.pairing == p)
            .filter_map(|r| r.outcome.as_ref().ok())
            .collect();
        let total: Duration = runs.iter().map(|r| r.elapsed).sum();
        let slowest = match runs.iter().max_by_key(|r| r.elapsed) {
            Some(r) => format!("`{}` at {:.1} s", r.case_id, r.elapsed.as_secs_f64()),
            None => "-".to_string(),
        };
        s.push_str(&format!(
            "| {p} | {} | {:.0} s | {slowest} |\n",
            runs.len(),
            total.as_secs_f64()
        ));
    }
    s
}

/// The Markdown case list `docs/interop-matrix.md` is regenerated from.
pub fn case_table() -> String {
    let mut s = String::new();
    s.push_str("| Case | Group | Configuration |\n|---|---|---|\n");
    for c in all_cases() {
        s.push_str(&format!(
            "| `{}` | {} | {} |\n",
            c.id,
            c.group,
            c.summary.replace('|', "\\|")
        ));
    }
    s
}

/// One row of the report: the outcome of one (case, pairing), failure included.
#[derive(Clone, Debug)]
pub struct CaseResult {
    /// [`InteropCase::id`].
    pub case_id: String,
    /// Which pairing ran.
    pub pairing: Pairing,
    /// The run, or why it failed (the message starts with the full configuration).
    pub outcome: Result<RunReport, String>,
}

impl CaseResult {
    /// True when the run passed.
    pub fn passed(&self) -> bool {
        self.outcome.is_ok()
    }

    /// The cell this result contributes to [`result_table`].
    pub fn cell(&self) -> String {
        match &self.outcome {
            Ok(r) => r.status(),
            Err(_) => "**FAIL**".to_string(),
        }
    }
}

/// The Markdown results table: one row per case, one column per pairing. A (case, pairing) with
/// no result at all is a failure, not a blank: a run that never happened proves nothing.
pub fn result_table(results: &[CaseResult]) -> String {
    let mut s = String::new();
    s.push_str("| Case |");
    for p in PAIRINGS {
        s.push_str(&format!(" {p} |"));
    }
    s.push_str("\n|---|");
    for _ in PAIRINGS {
        s.push_str("---|");
    }
    s.push('\n');

    let mut ids: Vec<&str> = Vec::new();
    for r in results {
        if !ids.contains(&r.case_id.as_str()) {
            ids.push(&r.case_id);
        }
    }
    for id in ids {
        s.push_str(&format!("| `{id}` |"));
        for p in PAIRINGS {
            let cell = results
                .iter()
                .find(|r| r.case_id == id && r.pairing == p)
                .map(CaseResult::cell)
                .unwrap_or_else(|| "**FAIL** (not run)".to_string());
            s.push_str(&format!(" {cell} |"));
        }
        s.push('\n');
    }
    s
}

// ---------------------------------------------------------------------------------------
// The environment stamp
// ---------------------------------------------------------------------------------------

/// The four binaries a full matrix run uses.
const REPORTED_BINARIES: [(Impl, &str); 4] = [
    (Impl::Go, "client"),
    (Impl::Go, "server"),
    (Impl::Rust, "client"),
    (Impl::Rust, "server"),
];

/// `date -u`, or an empty string if `date` is not there. Committed reports say when they ran, and
/// no crate in this workspace carries a clock library.
fn utc_now() -> String {
    std::process::Command::new("date")
        .args(["-u", "+%Y-%m-%d %H:%M:%SZ"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default()
}

/// The first 16 hex digits of a file's SHA-256, so a report names the exact binaries that ran.
fn file_digest(path: &std::path::Path) -> String {
    match std::fs::read(path) {
        Ok(bytes) => {
            let mut h = Sha256::new();
            h.update(&bytes);
            hex::encode(h.finalize())[..16].to_string()
        }
        Err(e) => format!("unreadable: {e}"),
    }
}

/// What `<bin> -v` prints, on one line.
fn binary_version(path: &std::path::Path) -> String {
    std::process::Command::new(path)
        .arg("-v")
        .output()
        .ok()
        .map(|o| {
            let mut s = String::from_utf8_lossy(&o.stdout).trim().to_string();
            if s.is_empty() {
                s = String::from_utf8_lossy(&o.stderr).trim().to_string();
            }
            s
        })
        .unwrap_or_else(|| "unknown".to_string())
}

/// `path` relative to the workspace root when it is inside it, so a committed report does not
/// carry the home directory of whoever ran it.
fn short_path(path: &std::path::Path) -> String {
    path.strip_prefix(crate::bins::workspace_root())
        .unwrap_or(path)
        .display()
        .to_string()
}

/// A Markdown table naming the host and the four binaries that ran, with their digests.
pub fn environment_table() -> String {
    let mut s = String::new();
    s.push_str("| Binary | Path | `-v` | SHA-256 (first 8 bytes) |\n|---|---|---|---|\n");
    for (which, name) in REPORTED_BINARIES {
        let row = match crate::bins::bin(which, name) {
            Ok(path) => format!(
                "| {which} {name} | `{}` | {} | `{}` |\n",
                short_path(&path),
                binary_version(&path),
                file_digest(&path)
            ),
            Err(e) => format!(
                "| {which} {name} | not found | - | - |\n<!-- {} -->\n",
                e.to_string().replace('\n', " ")
            ),
        };
        s.push_str(&row);
    }
    s
}

/// Opens a platform's section in `docs/interop-matrix.md`; see [`merge`].
pub const PLATFORM_MARKER: &str = "<!-- platform: ";

/// This machine's key in that document, e.g. `macos/aarch64`.
pub fn platform_key() -> String {
    format!("{}/{}", std::env::consts::OS, std::env::consts::ARCH)
}

/// The part of the document that comes from the code alone: the title, how the file is produced,
/// what the cells mean, and the case list.
///
/// It is rewritten from scratch on every run, so the committed file can never drift from
/// [`all_cases`].
pub fn preamble() -> String {
    let mut s = String::new();
    s.push_str("# Go ↔ Rust interop matrix\n\n");
    s.push_str(
        "Plan step 09.4. Every case below runs the real `kcptun-client` and `kcptun-server` \
         binaries on loopback in **all four pairings**: `go->rs` and `rs->go` are the interop \
         crossings, `go->go` and `rs->rs` are **controls**. A control that fails means the \
         harness is wrong, not the port: `go->go` runs no Rust at all.\n\n",
    );
    s.push_str(
        "Regenerate one platform's section (the others are kept):\n\n```sh\ncargo build \
         --release -p kcptun-client -p kcptun-server\ntools/fetch-reference.sh --skip-latest \
         --skip-tests\nKCPTUN_INTEROP_MATRIX_OUT=docs/interop-matrix.md \\\n  cargo test -p \
         kcptun-interop-tests --test interop_matrix -- --ignored --nocapture \
         interop_matrix_full\n```\n\n",
    );
    s.push_str(
        "`ok` means every byte of every workload arrived and neither process logged anything \
         unexpected. `ok (V11 a/b)` and `ok (V04+V11 a/b)` mean the same, except that the \
         half-close probe was allowed to come back short and `a` of its `b` bytes did.\n\n",
    );
    s.push_str(
        "Those two tags are the **only** tolerated difference, they apply only to the half-close \
         probe, and only with a **Go client**:\n\n\
         * **V11**: Go's smux discards received-but-unread data when the peer's FIN completes a \
         half-close (`tryHalfCloseCleanup` → `streamClosed` → `recycleTokens`), so the answer is \
         cut, usually at a frame boundary.\n\
         * **V04**, with `-QPP` on top, Go's `std.QPPPort` implements no `CloseWrite`, so \
         kcptun's `Pipe` falls back to `Close()` and tears the whole stream down; nothing of the \
         answer survives, hence the `0/…` rows.\n\n\
         Both reproduce in the `go->go` control. Every byte that *does* arrive is still checked \
         against the expected stream, so a truncation can never hide corruption, and a **Rust \
         client is held to a complete response against either server**: that is what V11 and \
         V04 bought. `b/b` on a V11 row means the expected truncation happened not to occur that \
         run: it is a race inside Go, not a difference between the peers. A V11 row is only ever \
         a statement that what arrived was a correct prefix: `0/b` would be accepted too, so a \
         run that produces one carries a note saying to compare it with its `go->go` control.\n\n",
    );
    s.push_str("## Cases\n\n");
    s.push_str(&case_table());
    s.push_str(
        "\nOne case can be re-run on its own, in all four pairings, with \
         `KCPTUN_INTEROP_MATRIX_FILTER=<case id>`.\n\n",
    );
    s
}

/// One platform's section of the document, opened by its [`PLATFORM_MARKER`].
pub fn section(results: &[CaseResult], workload: &Workload) -> String {
    let passed = results.iter().filter(|r| r.passed()).count();
    let key = platform_key();
    let mut s = format!("{PLATFORM_MARKER}{key} -->\n");
    s.push_str(&format!("## {key}: {}\n\n", utc_now()));
    s.push_str(&format!(
        "**{passed}/{total}** runs passed.\n\n",
        total = results.len()
    ));
    s.push_str(&format!(
        "Workload per run: {bulk} each way on one bulk stream, {streams} concurrent streams of \
         {sb} each way, and a half-close probe that asks for {rb} after `shutdown(SHUT_WR)` \
         (having waited {delay:?} first, so the answer and the peer's FIN are both buffered): \
         all SHA-256 verified, with both processes' logs scanned afterwards. The harness adds \
         `-closewait 0` to the server so teardown is not delayed by 30 s per direction; nothing \
         else is added to a case's flags.\n\n",
        bulk = bytes_human(workload.bulk_bytes),
        streams = workload.streams,
        sb = bytes_human(workload.stream_bytes),
        rb = bytes_human(workload.response_bytes),
        delay = workload.half_close_read_delay,
    ));

    s.push_str("### Binaries\n\n");
    s.push_str(&environment_table());

    s.push_str("\n### Results\n\n");
    s.push_str(&result_table(results));

    s.push_str("\n### Time per pairing\n\n");
    s.push_str(&timing_table(results));

    let failures: Vec<&CaseResult> = results.iter().filter(|r| !r.passed()).collect();
    if failures.is_empty() {
        s.push_str("\nNo failures.\n\n");
    } else {
        s.push_str(&format!("\n### Failures ({})\n\n", failures.len()));
        for f in failures {
            if let Err(e) = &f.outcome {
                s.push_str(&format!("```text\n{e}\n```\n\n"));
            }
        }
    }
    s
}

/// The platform key a section opens with, if it has one.
fn section_key(section: &str) -> Option<String> {
    section
        .strip_prefix(PLATFORM_MARKER)
        .and_then(|rest| rest.split_once(" -->"))
        .map(|(key, _)| key.trim().to_string())
}

/// Splits a document into its platform sections, dropping everything before the first one.
fn split_sections(doc: &str) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for (i, _) in doc.match_indices(PLATFORM_MARKER) {
        // Only a marker that starts its own line opens a section.
        if i != 0 && !doc[..i].ends_with('\n') {
            continue;
        }
        if let Some(last) = out.last_mut() {
            let start = doc.len() - last.len();
            *last = doc[start..i].to_string();
        }
        out.push(doc[i..].to_string());
    }
    out
}

/// The whole `docs/interop-matrix.md`: a freshly generated [`preamble`], then one section per
/// platform, with **this** platform's replaced by `section` and the others kept verbatim.
///
/// That is what lets one committed file carry both the laptop run and the lab-arm64 run while
/// staying a generated artefact: re-running the matrix on macOS rewrites the macOS section and
/// leaves the Linux one alone, and vice versa.
pub fn merge(existing: Option<&str>, section: &str) -> String {
    let key = section_key(section).unwrap_or_else(platform_key);
    let mut sections: Vec<(String, String)> = existing
        .map(split_sections)
        .unwrap_or_default()
        .into_iter()
        .filter_map(|c| section_key(&c).map(|k| (k, c)))
        .collect();
    match sections.iter_mut().find(|(k, _)| *k == key) {
        Some(slot) => slot.1 = section.to_string(),
        None => sections.push((key, section.to_string())),
    }
    let mut s = preamble();
    for (_, text) in sections {
        s.push_str(text.trim_end());
        s.push_str("\n\n");
    }
    s
}

/// [`merge`] of this run's [`section`] into `existing`.
pub fn report(existing: Option<&str>, results: &[CaseResult], workload: &Workload) -> String {
    merge(existing, &section(results, workload))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    use crate::matrix::first_uncovered_pair;

    #[test]
    fn the_case_list_is_deterministic_and_complete() {
        let a = all_cases();
        let b = all_cases();
        assert_eq!(a, b, "the matrix must not depend on anything but the code");
        assert_eq!(crypt_cases().len(), 15);
        assert_eq!(a.iter().filter(|c| c.group == Group::Production).count(), 1);
        let ids: BTreeSet<&str> = a.iter().map(|c| c.id.as_str()).collect();
        assert_eq!(ids.len(), a.len(), "case ids identify cases");
        for c in &a {
            assert_eq!(c.client.qpp, c.server.qpp, "{}: QPP must agree", c.id);
            assert_eq!(c.client.crypt, c.server.crypt, "{}: crypt must agree", c.id);
            assert_eq!(
                c.client.smuxver, c.server.smuxver,
                "{}: smuxver must agree",
                c.id
            );
            assert_eq!(c.client.mtu, c.server.mtu, "{}: mtu must agree", c.id);
            if c.qpp() {
                assert!(
                    c.key.len() >= 211,
                    "{}: a QPP case needs a key of at least qpp.QPPMinimumSeedLength(8) bytes",
                    c.id
                );
            }
        }
    }

    #[test]
    fn every_crypt_mode_gets_a_default_case() {
        let cases = crypt_cases();
        for (case, crypt) in cases.iter().zip(CRYPT_MODES) {
            assert_eq!(case.client.crypt, crypt);
            assert_eq!(case.client, Case::new().crypt(crypt), "otherwise default");
            assert_eq!(case.id, format!("crypt/{crypt}"));
        }
        // The same 15 names the kcp interop suite uses, so a mode can never be covered in one
        // place and forgotten in the other.
        let ours: BTreeSet<&str> = CRYPT_MODES.into_iter().collect();
        let theirs: BTreeSet<&str> = crate::kcp::CRYPT_MODES.into_iter().collect();
        assert_eq!(ours, theirs);
    }

    #[test]
    fn the_pairwise_group_covers_every_pair() {
        let levels: Vec<usize> = DIMENSIONS.iter().map(|d| d.levels.len()).collect();
        assert_eq!(levels, [2, 2, 4, 3, 4, 2, 2]);
        let rows = pairwise_indices(&levels);
        assert_eq!(first_uncovered_pair(&levels, &rows), None);
        let cases = pairwise_cases();
        assert_eq!(cases.len(), rows.len());
        // Far smaller than the exhaustive product, and big enough to hold every pair.
        let product: usize = levels.iter().product();
        assert_eq!(product, 768);
        assert!(cases.len() >= 16 && cases.len() <= 32, "{}", cases.len());

        // Spot-check that the values really reach the command lines.
        assert!(cases.iter().any(|c| c.client.smuxver == 1));
        assert!(cases.iter().any(|c| c.client.nocomp));
        assert!(cases.iter().any(|c| c.client.conn == 4));
        assert!(cases.iter().any(|c| c.client.mtu == 1400));
        assert!(cases.iter().any(|c| c.client.mode == "manual"));
        assert!(
            cases
                .iter()
                .any(|c| (c.client.ds, c.client.ps) == (10, 3)
                    && (c.server.ds, c.server.ps) == (5, 2)),
            "the FEC mismatch case must exist"
        );
        assert!(
            cases
                .iter()
                .any(|c| c.client.extra.windows(2).any(|w| w == ["-QPPCount", "61"]))
        );
        assert!(
            cases
                .iter()
                .any(|c| c.client.extra.windows(2).any(|w| w == ["-QPPCount", "7"]))
        );
        // A manual-mode case carries the four knobs kcptun's ApplyMode() would otherwise set.
        let manual = cases.iter().find(|c| c.client.mode == "manual").unwrap();
        let args = manual.client.args(Side::Client);
        for flag in ["-nodelay", "-interval", "-resend", "-nc"] {
            assert!(args.iter().any(|a| a == flag), "{flag} in {args:?}");
        }
    }

    #[test]
    fn the_production_profile_is_the_plans_profile() {
        let c = production_case();
        assert_eq!(c.client.crypt, "xor");
        assert_eq!(c.client.mode, "normal");
        assert_eq!(c.client.mtu, 1390);
        assert_eq!(c.client.smuxver, 2);
        assert_eq!((c.client.ds, c.client.ps), (0, 0));
        assert!(c.client.nocomp && c.server.nocomp);
        assert_eq!(c.client.conn, 4);
        let ca = c.client.args(Side::Client).join(" ");
        let sa = c.server.args(Side::Server).join(" ");
        for expected in [
            "-sndwnd 8192",
            "-rcvwnd 8192",
            "-smuxbuf 16777216",
            "-streambuf 16777216",
            "-quiet",
        ] {
            assert!(ca.contains(expected), "client: {ca}");
            assert!(sa.contains(expected), "server: {sa}");
        }
        assert!(ca.contains("-sockbuf 8388608"), "{ca}");
        assert!(sa.contains("-sockbuf 67108868"), "{sa}");
        assert!(!sa.contains("-conn"), "the server has no -conn: {sa}");
    }

    #[test]
    fn the_qpp_key_clears_gos_minimum_seed_length() {
        let k = qpp_key();
        assert_eq!(k.len(), QPP_KEY_LEN);
        assert_eq!(k, qpp_key(), "deterministic");
        // Go: qpp.QPPMinimumSeedLength(8) == 211 (the byte length of log2(256!)).
        assert!(k.len() >= 211);
        assert!(k.chars().all(|c| c.is_ascii_graphic()), "{k}");
    }

    #[test]
    fn expectations_follow_v11_and_v04() {
        let plain = &crypt_cases()[0];
        let qpp = pairwise_cases()
            .into_iter()
            .find(|c| c.qpp())
            .expect("a QPP case");
        for p in PAIRINGS {
            let want = match p.client {
                // V11 applies to a Go client with or without QPP.
                Impl::Go => Expectation::GoSmuxTruncation,
                Impl::Rust => Expectation::Complete,
            };
            assert_eq!(Expectation::of(plain, p), want, "{p} without QPP");
            let want = match p.client {
                Impl::Go => Expectation::GoQppTruncation,
                Impl::Rust => Expectation::Complete,
            };
            assert_eq!(Expectation::of(&qpp, p), want, "{p} with QPP");
        }
        // The Rust client stays strict against a Go server, QPP or not: that is what the two
        // decisions bought.
        let rs_go = Pairing {
            client: Impl::Rust,
            server: Impl::Go,
        };
        assert_eq!(Expectation::of(&qpp, rs_go), Expectation::Complete);
        assert_eq!(Expectation::of(plain, rs_go), Expectation::Complete);
        assert!(!Expectation::Complete.allows_truncation());
        assert!(Expectation::GoSmuxTruncation.allows_truncation());
        assert!(Expectation::GoQppTruncation.allows_truncation());
        assert_eq!(
            [
                Expectation::Complete.tag(),
                Expectation::GoSmuxTruncation.tag(),
                Expectation::GoQppTruncation.tag()
            ],
            ["complete", "V11", "V04+V11"]
        );
    }

    #[test]
    fn pairings_name_the_controls() {
        assert_eq!(PAIRINGS.len(), 4);
        let labels: Vec<String> = PAIRINGS.iter().map(|p| p.label()).collect();
        assert_eq!(labels, ["go->rs", "rs->go", "go->go", "rs->rs"]);
        assert_eq!(
            PAIRINGS.iter().filter(|p| p.is_control()).count(),
            2,
            "go->go and rs->rs"
        );
    }

    #[test]
    fn target_headers_round_trip() {
        for mode in [
            TargetMode::Echo,
            TargetMode::Respond {
                seed: 0xdead_beef,
                len: 1 << 20,
            },
        ] {
            assert_eq!(TargetMode::parse(&mode.header()), Some(mode));
        }
        let mut h = TargetMode::Echo.header();
        h[0] = b'X';
        assert_eq!(TargetMode::parse(&h), None, "wrong magic");
        let mut h = TargetMode::Echo.header();
        h[4] = 9;
        assert_eq!(TargetMode::parse(&h), None, "unknown mode");
    }

    #[test]
    fn error_markers_pass_a_healthy_log_and_catch_a_sick_one() {
        let healthy = "\
2026/09/23 10:16:09 main.rs:204: Listening on: 127.0.0.1:24777/udp
2026/09/23 10:16:12 main.rs:353: remote address: 127.0.0.1:53857
2026/09/23 10:16:12 main.rs:390: smux version: 2 on connection: 127.0.0.1:24777 -> 127.0.0.1:53857
2026/09/23 10:16:12 main.rs:568: stream opened in: 127.0.0.1:53857(3) out: 127.0.0.1:24778
2026/09/23 10:16:12 main.rs:593: stream closed in: 127.0.0.1:53857(3) out: 127.0.0.1:24778
2026/09/23 10:16:12 main.go:385: initiating key derivation
2026/09/23 10:16:12 main.go:387: key derivation done
2026/09/23 10:16:12 main.go:336: encryption: aes
2026/09/23 10:16:12 main.go:337: QPP: true
2026/09/23 10:16:12 main.go:345: datashard: 10 parityshard: 3
2026/09/23 10:16:12 main.go:352: keepalive: 10
";
        assert!(
            error_lines(healthy).is_empty(),
            "{:?}",
            error_lines(healthy)
        );
        let sick = format!(
            "{healthy}2026/09/23 10:16:13 main.go:545: pipe: io: read/write on closed pipe in: x out: y\n"
        );
        assert_eq!(error_lines(&sick).len(), 1);
        assert_eq!(error_lines("QPP Warning: QPPCount 4").len(), 1);
        assert_eq!(error_lines("re-connecting: dial(): nope").len(), 1);
    }

    /// A minimal set of results for the document tests.
    fn sample_results() -> Vec<CaseResult> {
        PAIRINGS
            .iter()
            .map(|&pairing| CaseResult {
                case_id: "crypt/aes".to_string(),
                pairing,
                outcome: Ok(RunReport {
                    case_id: "crypt/aes".to_string(),
                    pairing,
                    expectation: Expectation::Complete,
                    half_close_bytes: 1024,
                    response_bytes: 1024,
                    elapsed: Duration::from_millis(500),
                    notes: Vec::new(),
                }),
            })
            .collect()
    }

    #[test]
    fn a_section_is_tagged_with_its_platform() {
        let s = section(&sample_results(), &SMOKE);
        assert!(s.starts_with(&format!("{PLATFORM_MARKER}{} -->\n", platform_key())));
        assert!(s.contains(&format!("## {}: ", platform_key())));
        assert!(s.contains("**4/4** runs passed."));
        assert!(s.contains("### Results"), "{s}");
        assert!(s.contains("No failures."));
        assert_eq!(section_key(&s).as_deref(), Some(platform_key().as_str()));
        assert_eq!(section_key("no marker here"), None);
    }

    #[test]
    fn merging_keeps_the_other_platforms_sections() {
        let other = format!(
            "{PLATFORM_MARKER}sunos/sparc64 -->\n## sunos/sparc64: long ago\n\nnothing to see\n"
        );
        let mine = section(&sample_results(), &SMOKE);

        // A fresh document: preamble plus this platform's section.
        let doc = merge(None, &mine);
        assert!(doc.starts_with("# Go ↔ Rust interop matrix\n"));
        assert!(doc.contains("## Cases"));
        assert_eq!(split_sections(&doc).len(), 1);

        // An existing document with a foreign section keeps it, and ours is appended.
        let doc = merge(Some(&format!("{}{other}", preamble())), &mine);
        let keys: Vec<Option<String>> = split_sections(&doc)
            .iter()
            .map(|s| section_key(s))
            .collect();
        assert_eq!(
            keys,
            [Some("sunos/sparc64".to_string()), Some(platform_key())]
        );
        assert!(doc.contains("nothing to see"));

        // Running again replaces only our section, in place.
        let again = merge(Some(&doc), &mine);
        let keys: Vec<Option<String>> = split_sections(&again)
            .iter()
            .map(|s| section_key(s))
            .collect();
        assert_eq!(
            keys,
            [Some("sunos/sparc64".to_string()), Some(platform_key())]
        );
        assert_eq!(again.matches("nothing to see").count(), 1);
        assert_eq!(again.matches("### Results").count(), 1);
        // The preamble is regenerated, so the committed case list can never go stale.
        assert!(again.contains("| `pair/16` | pairwise |"));
        // `report` is `merge` over a freshly rendered `section`, so it is the same document,
        // except for the `## <platform>: <time>` header, whose second-resolution clock may have
        // ticked since `mine` was built. That one line is normalised away rather than compared.
        let fresh = report(Some(&doc), &sample_results(), &SMOKE);
        assert_eq!(without_section_times(&fresh), without_section_times(&again));
    }

    /// Replaces every `## <platform>: <time>` header with a fixed line, so two renderings taken
    /// at different instants can be compared.
    fn without_section_times(doc: &str) -> String {
        doc.lines()
            .map(|line| {
                if line.starts_with("## ") && line.contains(": ") {
                    "## <platform>: <time>"
                } else {
                    line
                }
            })
            .collect::<Vec<_>>()
            .join("\n")
    }

    #[test]
    fn byte_counts_read_well() {
        assert_eq!(bytes_human(20 * 1000 * 1000), "20 MB");
        assert_eq!(bytes_human(256 * 1024), "256 KiB");
        assert_eq!(bytes_human(1024), "1 KiB");
        assert_eq!(bytes_human(4095), "4095 B");
        assert_eq!(bytes_human(0), "0 B");
    }

    #[test]
    fn the_timing_table_covers_every_pairing() {
        let t = timing_table(&[]);
        assert_eq!(t.lines().count(), PAIRINGS.len() + 2);
        for p in PAIRINGS {
            assert!(t.contains(&format!("| {p} | 0 | 0 s | - |")), "{t}");
        }
    }

    #[test]
    fn the_case_table_is_markdown() {
        let t = case_table();
        assert!(t.starts_with("| Case | Group | Configuration |\n|---|---|---|\n"));
        assert_eq!(t.lines().count(), all_cases().len() + 2);
        assert!(t.contains("| `crypt/aes` | crypt |"));
        assert!(t.contains("| `production` | production |"));
        assert!(t.contains("| `pair/01` | pairwise |"));
    }

    #[test]
    fn the_result_table_has_one_column_per_pairing() {
        let results: Vec<CaseResult> = PAIRINGS
            .iter()
            .map(|&pairing| CaseResult {
                case_id: "crypt/aes".to_string(),
                pairing,
                outcome: Ok(RunReport {
                    case_id: "crypt/aes".to_string(),
                    pairing,
                    expectation: Expectation::Complete,
                    half_close_bytes: 1024,
                    response_bytes: 1024,
                    elapsed: Duration::from_secs(1),
                    notes: Vec::new(),
                }),
            })
            .collect();
        let t = result_table(&results);
        assert!(t.starts_with("| Case | go->rs | rs->go | go->go | rs->rs |\n"));
        assert!(t.contains("| `crypt/aes` | ok | ok | ok | ok |"), "{t}");
        // A missing run is a failure, not a blank.
        let t = result_table(&results[..2]);
        assert!(
            t.contains("| `crypt/aes` | ok | ok | **FAIL** (not run) | **FAIL** (not run) |"),
            "{t}"
        );
        // A failed run is loud.
        let mut failed = results.clone();
        failed[0].outcome = Err("boom".to_string());
        assert!(result_table(&failed).contains("| **FAIL** |"));
        assert!(!failed[0].passed() && failed[1].passed());

        // A truncating run says how much of the answer survived, right in the cell.
        let mut truncated = results[0].clone();
        if let Ok(r) = &mut truncated.outcome {
            r.expectation = Expectation::GoSmuxTruncation;
            r.half_close_bytes = 512;
            r.notes.push("client logged `pipe:`".to_string());
        }
        let report = truncated.outcome.as_ref().expect("ok");
        assert_eq!(report.status(), "ok (V11 512/1024)");
        assert_eq!(report.detail(), "ok (V11 512/1024) [client logged `pipe:`]");
        assert_eq!(truncated.cell(), "ok (V11 512/1024)");
    }

    #[test]
    fn select_filters_by_id() {
        assert_eq!(select(all_cases(), "").len(), all_cases().len());
        assert_eq!(select(all_cases(), "production").len(), 1);
        assert_eq!(select(all_cases(), "crypt/").len(), 15);
        assert!(select(all_cases(), "nope").is_empty());
    }

    #[test]
    fn a_failing_case_prints_its_configuration() {
        let c = production_case();
        let d = c.describe();
        assert!(d.contains("case production"));
        assert!(d.contains("client flags: -crypt xor"));
        assert!(d.contains("server flags: -crypt xor"));
        assert!(d.contains("-sockbuf 67108868"));
        // A QPP case must not dump 300 bytes of key into every failure message.
        let qpp = pairwise_cases().into_iter().find(|c| c.qpp()).unwrap();
        let d = qpp.describe();
        assert!(d.contains("(300 bytes)"), "{d}");
        assert!(!d.contains(&qpp.key), "the whole key is elided");
    }
}
