//! Go's `syscall.Errno` error text, ported from Go's own tables (**DECISIONS D30**).
//!
//! Go does not call `strerror(3)`. Every `syscall.Errno` renders itself from a table the Go
//! distribution generates per `GOOS`/`GOARCH` — `syscall/zerrors_linux_amd64.go` line 1453 is
//! `98: "address already in use"` — and falls back to `"errno " + itoa(n)` for anything that
//! table has no text for (`syscall/syscall_unix.go`, `func (e Errno) Error()`).
//!
//! Taking the C library's message instead only ever *looked* right, because glibc happens to
//! agree with Go for the common errnos. Step 10.5 found where it does not: a **static musl**
//! build's `strerror` spells `EADDRINUSE` `Address in use` where glibc's spells it
//! `Address already in use`; Go's table entry is the lower-case `address already in use`. So
//! `kcptun-server -l :29900` on a port already taken printed `bind: address in use` on musl
//! where Go prints `bind: address already in use`. musl is the container image's libc and a
//! shipped artifact (D07), so
//! that was the binary most users would actually run. The port's log lines are a byte-for-byte
//! contract (`docs/porting-guide.md` §4, and the CLI differential of step 09.5), and a contract
//! that is target-dependent is no contract — so the table is ported, which is also simply what
//! Go does.
//!
//! [`go_error_text`] is the single renderer: `kcptun_std::config::go_error_text` (and through it
//! Go's `*net.OpError` builders in `kcptun_std::mainutil`) and `kcptun_tcpraw::addr::errno_text`
//! are thin wrappers over it. It lives in this crate rather than in `kcptun-std` — where D30
//! puts it — only because `kcptun-std` *depends on* `kcptun-tcpraw`, which needs the same
//! renderer; `kcptun-kcp` is the crate both can reach, and it already hosts the ports of Go's
//! `net` (`addr`) and `sort` (`gosort`). `kcptun_std::goerrno` re-exports this module, so D30's
//! name still resolves.
//!
//! **Platform coverage.** The tables carried are the ones of DECISIONS D22: Linux on
//! `x86_64`/`x86`/`aarch64`/`arm`, macOS on `x86_64`/`aarch64`, and FreeBSD on `x86_64`. Any
//! other target keeps the previous behaviour — the C library's message, lower-cased — because
//! shipping an unverified table would be worse than the libc text it replaces: Linux `mips`, for
//! one, numbers its errnos differently (`EADDRINUSE` is 125 there), so the generic table would
//! name the wrong error rather than merely word it differently. [`has_table`] reports which
//! applies.
//!
//! The table itself is in [`table`], generated by `tools/gen-errno-table.py` from
//! `testdata/vectors/errno.json` (`tools/govectors` area `errno`, which reads Go's own
//! `zerrors_*.go`) and checked against that vector file — for *every* platform, not only the
//! host's — by `tests::vectors_errno_tables`.
// Go: go1.27.1 syscall/syscall_unix.go:(Errno).Error(), syscall/zerrors_<goos>_<goarch>.go

use std::io;

mod table;
#[cfg(test)]
mod tests;

// ---------------------------------------------------------------------------------------
// The table of the target being compiled for
// ---------------------------------------------------------------------------------------

// Go's `errors` array for this target, split in two so that the entries every GOARCH of a
// GOOS shares are stored once: index `i` is `HEAD[i]`, or `TAIL[i - HEAD.len()]` beyond it.
// Both are empty on a target whose table is not carried (see the module docs).

/// Entries 0..`HEAD.len()` of Go's `errors` array for this target.
#[cfg(all(
    target_os = "linux",
    any(
        target_arch = "x86_64",
        target_arch = "x86",
        target_arch = "aarch64",
        target_arch = "arm"
    )
))]
const HEAD: &[&str] = &table::LINUX;
/// Entries 0..`HEAD.len()` of Go's `errors` array for this target.
#[cfg(target_os = "macos")]
const HEAD: &[&str] = &table::DARWIN;
/// Entries 0..`HEAD.len()` of Go's `errors` array for this target.
#[cfg(all(target_os = "freebsd", target_arch = "x86_64"))]
const HEAD: &[&str] = &table::FREEBSD;
/// No table is carried for this target, so [`go_error_text`] keeps the C library's message.
#[cfg(not(any(
    all(
        target_os = "linux",
        any(
            target_arch = "x86_64",
            target_arch = "x86",
            target_arch = "aarch64",
            target_arch = "arm"
        )
    ),
    target_os = "macos",
    all(target_os = "freebsd", target_arch = "x86_64")
)))]
const HEAD: &[&str] = &[];

/// The entries this GOARCH has beyond the ones its GOOS shares.
#[cfg(all(target_os = "linux", target_arch = "aarch64"))]
const TAIL: &[&str] = &table::LINUX_TAIL_ARM64;
/// The entries this GOARCH has beyond the ones its GOOS shares.
#[cfg(all(target_os = "linux", target_arch = "arm"))]
const TAIL: &[&str] = &table::LINUX_TAIL_ARM;
/// The entries this GOARCH has beyond the ones its GOOS shares.
#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
const TAIL: &[&str] = &table::DARWIN_TAIL_ARM64;
/// This GOARCH's table ends where its GOOS's shared table does.
#[cfg(not(any(
    all(target_os = "linux", any(target_arch = "aarch64", target_arch = "arm")),
    all(target_os = "macos", target_arch = "aarch64")
)))]
const TAIL: &[&str] = &[];

// ---------------------------------------------------------------------------------------
// Lookups
// ---------------------------------------------------------------------------------------

/// Whether Go's table for this target is compiled in.
///
/// `false` means [`go_error_text`] falls back to the C library's message for an errno — see the
/// module docs for which targets those are.
pub const fn has_table() -> bool {
    !HEAD.is_empty()
}

/// The number of entries in Go's `errors` array for this target (0 when none is carried).
///
/// Go's array is indexed by errno, so this is one past the largest errno it names.
pub const fn table_len() -> usize {
    HEAD.len() + TAIL.len()
}

/// Go's text for `errno`, or `None` when the table has no text for it — either because this
/// target carries no table, or because Go's own array is empty at that index (it is sparse:
/// index 0 always, and 41 and 58 on Linux).
// Go: go1.27.1 syscall/zerrors_<goos>_<goarch>.go — `errors[e]`
pub fn errno_text(errno: i32) -> Option<&'static str> {
    let index = usize::try_from(errno).ok()?;
    let text = match HEAD.get(index) {
        Some(text) => *text,
        None => *TAIL.get(index.checked_sub(HEAD.len())?)?,
    };
    if text.is_empty() { None } else { Some(text) }
}

/// Go's `syscall.Errno.Error()`: the table's text, or Go's own numeric form for an errno the
/// table does not name. `None` on a target whose table is not carried.
// Go: go1.27.1 syscall/syscall_unix.go:(Errno).Error()
pub fn errno_error(errno: i32) -> Option<String> {
    if !has_table() {
        return None;
    }
    match errno_text(errno) {
        Some(text) => Some(text.to_string()),
        // Go: `return "errno " + itoa.Itoa(int(e))` — not the C library's "Unknown error N".
        None => Some(format!("errno {errno}")),
    }
}

/// Renders `err` the way Go renders it in a log line.
///
/// An error the operating system produced carries an errno, and Go spells it from its own table
/// ([`errno_error`]). Anything else — an `io::Error` this port built itself, or one Rust
/// synthesised without an errno — keeps its own text, with the first letter lower-cased and
/// Rust's ` (os error N)` suffix removed.
///
/// That last step is a heuristic, and it is deliberately confined to the fallback: it exists
/// only to make a C library message look like Go's table entry, which the table now does
/// properly. It still applies on a target with no table, and to the handful of texts Rust's
/// `std` writes itself (`failed to lookup address information: …`), which Go has no counterpart
/// for either way.
///
/// The fallback **does** also see errors whose text this port composed, because D30 routes every
/// log line through here: `kcptun_tcpraw`'s already-built `*net.OpError` strings (they carry no
/// `raw_os_error`, so they take this branch), `kcptun_kcp::addr`'s resolver messages, and smux's
/// own messages via `From<kcptun_smux::Error> for io::Error`. Lower-casing leaves all of those
/// alone only because `docs/porting-guide.md` §4 requires them to be Go's text, and Go's are
/// lower-case. The one capitalised exception is `kcptun_kcp::session::SessionError::OverheadTooLarge`,
/// whose `Display` is Go's panic string `Overhead too large`; it is unreachable from a log line
/// (`session.rs` checks the overhead against `IKCP_MTU_DEF`, not against `--mtu`). A future
/// port-chosen text that starts with a capital would be mangled here, so it must not be routed
/// through this function.
pub fn go_error_text(err: &io::Error) -> String {
    if let Some(errno) = err.raw_os_error()
        && let Some(text) = errno_error(errno)
    {
        return text;
    }
    platform_error_text(err)
}

/// The pre-D30 rendering: the platform's own message, lower-cased and without Rust's suffix.
fn platform_error_text(err: &io::Error) -> String {
    let text = err.to_string();
    let text = match text.rfind(" (os error ") {
        Some(i) if text.ends_with(')') => &text[..i],
        _ => text.as_str(),
    };
    let mut chars = text.chars();
    match chars.next() {
        Some(c) => c.to_lowercase().chain(chars).collect(),
        None => String::new(),
    }
}
