// Code generated by copying; DO NOT EDIT.
//
// Verbatim copy of github.com/xtaci/kcp-go/v5@v5.6.66 kcp_trace_off.go
// (reference/kcptun/vendor/github.com/xtaci/kcp-go/v5/kcp_trace_off.go), MIT License, Copyright (c) 2015
// xtaci. Used by tools/govectors to record golden KCP traces with an injected clock.
//
// Everything below the marker is byte-identical to the reference (TestVerbatimCopy).
// ---- verbatim below ----
//go:build !debug

// if build tag debug is not set, then debugLog will ingore in compile time
package kcp

func (kcp *KCP) debugLog(logtype KCPLogType, args ...any) {}
