#!/usr/bin/env python3
"""Regenerate crates/kcp/src/goerrno/table.rs from testdata/vectors/errno.json.

The vector file is written by `tools/gen-vectors.sh errno`, which reads Go's own generated
`syscall/zerrors_<goos>_<goarch>.go` tables out of the Go distribution (DECISIONS D30).
This script only reshapes them into Rust `const` arrays; the authoritative check that the
committed Rust table still matches Go is the unit test
`kcptun_kcp::goerrno::tests::vectors_errno_tables`, which runs in the normal gate.

Usage:
    tools/gen-errno-table.py            # rewrite crates/kcp/src/goerrno/table.rs
    tools/gen-errno-table.py --check    # exit 1 if the file would change (tree untouched)
"""

from __future__ import annotations

import json
import os
import pathlib
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
VECTORS = ROOT / "testdata" / "vectors" / "errno.json"
OUT = ROOT / "crates" / "kcp" / "src" / "goerrno" / "table.rs"

# Rust const name -> (base case, tail-of case or None).
#
# Go's Linux tables are identical for 0..=132 on every GOARCH the port targets and differ
# only in what follows, so the shared part is stored once and each GOARCH adds its own tail.
# Darwin is the same shape: arm64 has one entry (EQFULL) that amd64 does not.
LAYOUT = [
    ("LINUX", "linux/amd64", None),
    ("LINUX_TAIL_ARM64", "linux/arm64", "linux/amd64"),
    ("LINUX_TAIL_ARM", "linux/arm", "linux/amd64"),
    ("DARWIN", "darwin/amd64", None),
    ("DARWIN_TAIL_ARM64", "darwin/arm64", "darwin/amd64"),
    ("FREEBSD", "freebsd/amd64", None),
]

# GOOS/GOARCH -> the Rust consts that make up its table, head first.
TARGETS = [
    ("linux", "amd64", ["LINUX"]),
    ("linux", "386", ["LINUX"]),
    ("linux", "arm64", ["LINUX", "LINUX_TAIL_ARM64"]),
    ("linux", "arm", ["LINUX", "LINUX_TAIL_ARM"]),
    ("darwin", "amd64", ["DARWIN"]),
    ("darwin", "arm64", ["DARWIN", "DARWIN_TAIL_ARM64"]),
    ("freebsd", "amd64", ["FREEBSD"]),
]

HEADER = """\
//! Go's `syscall` error tables, one per target platform (DECISIONS D30).
//!
//! @generated by `tools/gen-errno-table.py` from `testdata/vectors/errno.json`, which
//! `tools/govectors` reads out of the Go distribution's own generated tables
//! (`$GOROOT/src/syscall/zerrors_<goos>_<goarch>.go`, `var errors = [...]string{}`).
//! Do not edit by hand. `super::tests::vectors_errno_tables` checks every table here
//! against that vector file on every `cargo test` run, on whatever platform it runs on.
//!
//! The index is the errno; an empty string is a hole in Go's own table, which
//! [`super::errno_error`] fills with Go's numeric form. Linux's table is identical for
//! errno 0..=LINUX_MAX on every GOARCH the port builds for (D22), so it is stored once and the
//! two GOARCHes that carry more get a tail; darwin is the same shape.
//!
//! These are `const`, not `static`: a build only materialises the table its own `cfg`
//! selects, and the rest cost nothing outside the test binary.
// Go: go1.27.1 syscall/zerrors_<goos>_<goarch>.go
// Every platform's table is compiled in so that one `cargo test` run, on any host, checks
// all of them against the vector file; only the `cfg`-selected one reaches a real build.
#![allow(dead_code)]
"""


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(cases: dict[str, list[str]]) -> str:
    out = [HEADER.replace("LINUX_MAX", str(len(cases["linux/amd64"]) - 1))]
    for name, case, tail_of in LAYOUT:
        rows = cases[case]
        start = 0
        if tail_of is not None:
            start = len(cases[tail_of])
            rows = rows[start:]
        goos = case.split("/")[0]
        if tail_of is None:
            doc = f"Go's `errors` table on {goos}, errno 0..={len(rows) - 1}."
        else:
            doc = f"What {case} has beyond the shared {goos} table, from errno {start}."
        out.append(f"/// {doc}")
        out.append(f"pub(super) const {name}: [&str; {len(rows)}] = [")
        for i, text in enumerate(rows):
            out.append(f"    /* {start + i} */ {rust_str(text)},")
        out.append("];")
        out.append("")

    out.append(
        "/// Every table this file carries, keyed the way `testdata/vectors/errno.json`\n"
        "/// names its cases, for the vector test."
    )
    out.append("#[cfg(test)]")
    out.append("pub(super) fn all() -> Vec<(&'static str, Vec<&'static str>)> {")
    out.append("    vec![")
    for goos, goarch, parts in TARGETS:
        joined = ", ".join(f"{p}.as_slice()" for p in parts)
        out.append(f'        ("{goos}/{goarch}", [{joined}].concat()),')
    out.append("    ]")
    out.append("}")
    return "\n".join(out) + "\n"


def rustfmt(text: str) -> str:
    """Runs the generated source through rustfmt, so `cargo fmt --check` stays green."""
    exe = shutil.which("rustfmt") or os.path.expanduser("~/.cargo/bin/rustfmt")
    if not os.path.exists(exe):
        raise SystemExit("gen-errno-table: rustfmt not found; put the pinned toolchain on PATH")
    done = subprocess.run(
        [exe, "--edition", "2024", "--emit", "stdout", "--quiet"],
        input=text,
        capture_output=True,
        text=True,
        check=True,
    )
    return done.stdout


def main() -> int:
    check = "--check" in sys.argv[1:]
    data = json.loads(VECTORS.read_text())
    if data.get("area") != "errno":
        print(f"gen-errno-table: {VECTORS} is not the errno area", file=sys.stderr)
        return 1
    cases = {c["name"]: c["errors"] for c in data["cases"]}
    missing = [c for _, c, _ in LAYOUT if c not in cases]
    if missing:
        print(f"gen-errno-table: missing cases {missing}", file=sys.stderr)
        return 1
    text = rustfmt(render(cases))
    if check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"gen-errno-table: {OUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
